﻿-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2017-03-16 16:26:07.779

use master
go
if exists(Select * from sys.databases where name=N'QuanLyBanHang')
	Drop database QuanLyBanHang
Go

Create database QuanLyBanHang
Go

Use QuanLyBanHang
Go
-- tables
-- Table: HOADON
CREATE TABLE HOADON (
    MAHD int  NOT NULL IDENTITY,
    NGAYLAPHD date  NOT NULL,
    MAKH int  NOT NULL,
    CONSTRAINT HOADON_pk PRIMARY KEY  (MAHD)
);
-- Table: SANPHAM
CREATE TABLE SANPHAM (
    TENSP nvarchar(50)  NOT NULL,
    DONGIA int  NOT NULL,
    MALOAISP int  NOT NULL,
    DONVI nvarchar(20)  NOT NULL,
    MASP int  NOT NULL IDENTITY,
    CONSTRAINT SANPHAM_pk PRIMARY KEY  (MASP)
);
-- Table: HOADON_CT
CREATE TABLE HOADON_CT (
    MAHD int  NOT NULL references HOADON(MAHD),
    MASP int  NOT NULL  references SANPHAM(MASP),
    SOLUONG int  NOT NULL,
    CONSTRAINT HOADON_CT_pk PRIMARY KEY  (MAHD,MASP)
);

-- Table: KHACHHANG
CREATE TABLE KHACHHANG (
    MAKH int  NOT NULL IDENTITY,
    TENKH nvarchar(30)  NOT NULL,
    DIACHI nvarchar(50)  NOT NULL,
    SDT int  NOT NULL,
    CONSTRAINT KHACHHANG_pk PRIMARY KEY  (MAKH)
);

-- Table: LOAI_SP
CREATE TABLE LOAI_SP (
    MALOAISP int  NOT NULL IDENTITY,
    TENLOAISP nvarchar(50)  NOT NULL,
    CONSTRAINT LOAI_SP_pk PRIMARY KEY  (MALOAISP)
);



-- Table: USERNAME
CREATE TABLE USERNAME (
    USERNAME nvarchar(50)  NOT NULL,
    PASSWORD nvarchar(50)  NOT NULL,
    CONSTRAINT USERNAME_pk PRIMARY KEY  (USERNAME)
);

-- foreign keys
-- Reference: HOADON_CT_HOADON (table: HOADON_CT)
ALTER TABLE HOADON_CT ADD CONSTRAINT HOADON_CT_HOADON
    FOREIGN KEY (MAHD)
    REFERENCES HOADON (MAHD);

-- Reference: HOADON_CT_SANPHAM (table: HOADON_CT)
ALTER TABLE HOADON_CT ADD CONSTRAINT HOADON_CT_SANPHAM
    FOREIGN KEY (MASP)
    REFERENCES SANPHAM (MASP);

-- Reference: HOADON_KHACHHANG (table: HOADON)
ALTER TABLE HOADON ADD CONSTRAINT HOADON_KHACHHANG
    FOREIGN KEY (MAKH)
    REFERENCES KHACHHANG (MAKH);

-- Reference: SANPHAM_LOAI_SP (table: SANPHAM)
ALTER TABLE SANPHAM ADD CONSTRAINT SANPHAM_LOAI_SP
    FOREIGN KEY (MALOAISP)
    REFERENCES LOAI_SP (MALOAISP);

-- End of file.
-- Bảng USERNAME.
INSERT INTO USERNAME VALUES('admin','admin')
INSERT INTO USERNAME VALUES('user','user')
-- Bảng KHACHHANG.
INSERT INTO KHACHHANG VALUES(N'Trần Vũ Hoàng',N'10 Trần Kế Xương, F.7, Q.Phú Nhuận, TP.HCM','0905919290')
INSERT INTO KHACHHANG VALUES(N'Trần Quang Huy',N'436A/63 đường 3/2, P12, Q10, HCM','01658601161')
INSERT INTO KHACHHANG VALUES(N'Hoàng Trung Tuấn',N'33/14 Bình Dường II An Bình Dĩ An','1869104611')
INSERT INTO KHACHHANG VALUES(N'Vũ Đình Thi',N'26, Đồng Đen, P14, Q. Tân Bình, HCM','01864840426')
INSERT INTO KHACHHANG VALUES(N'Võ Thanh Hà',N'45A Hòa Bình, P. Tân Thới Hòa, Q.Tân Phú, HCM','01266864347')

-- Bảng LOAI_SP.
INSERT INTO LOAI_SP VALUES(N'Máy Tính')
INSERT INTO LOAI_SP VALUES(N'Thiết Bị Tin Học')
INSERT INTO LOAI_SP VALUES(N'Thiết Bị Mạng')
INSERT INTO LOAI_SP VALUES(N'Thiết Bị Kỹ Thuật Số')
INSERT INTO LOAI_SP VALUES(N'Thiết Bị Văn Phòng')

-- BẢNG SANPHAM:
INSERT INTO SANPHAM VALUES(N'Laptop Macbook Pro MF841',40200000,1 ,N'Cái')
INSERT INTO SANPHAM VALUES(N'Bộ nhớ DDR3 Kingston 8GB',970000,2 ,N'Cái')
INSERT INTO SANPHAM VALUES(N'TPLink TL-WR841N',390000,3 ,N'Cái')
INSERT INTO SANPHAM VALUES(N'Camera eView IRD2803A10H',820000,4 ,N'Cái')
INSERT INTO SANPHAM VALUES(N'Máy in Canon Pixma E560',2500000,5 ,N'Bộ')

-- BẢNG HOADON:
INSERT INTO HOADON VALUES('2013-02-14',1)
INSERT INTO HOADON VALUES('2014-01-03',2)
INSERT INTO HOADON VALUES('2014-05-08',3)
INSERT INTO HOADON VALUES('2015-07-15',5)
INSERT INTO HOADON VALUES('2015-10-30',4)
INSERT INTO HOADON VALUES('2015-02-24',3)

-- BẢNG HOADON_CT:
INSERT INTO HOADON_CT VALUES(1,1,1)
INSERT INTO HOADON_CT VALUES(2,2,2)
INSERT INTO HOADON_CT VALUES(3,3,1)
INSERT INTO HOADON_CT VALUES(4,4,1)
INSERT INTO HOADON_CT VALUES(5,5,10)
INSERT INTO HOADON_CT VALUES(6,4,10)
INSERT INTO HOADON_CT VALUES(6,5,10)